### ISSUE TITLE
ID1.1.0a Edit client information

### ISSUE THREAD

**Issue by mack1070101** [CMPUT401/vettr_server#41]
I want to be able to edit client information

**Comment by mack1070101** [comment]
Back end is complete

**Comment by MarcOlivierLajeunesse** [comment]
Front-end complete. Needs testing. For acceptance tests, might do human-read scripts.

**Comment by MarcOlivierLajeunesse** [comment]
Finished acceptance tests. Made with a human read script Human_read_script_to_test_editing_client_information.txt . It contains 64 checks. 6 Fail, and 58 Pass. The failures are cause when the user goes to edit the clients, <br> tags are displayed in the address and notes fields when they should not be. Should be fixed in next sprint.
